# Target host
host = http://localhost:2025

# Load configuration
users = 50
spawn-rate = 10
run-time = 1m

# Web UI Dashboard on local host
web-port = 8090

# CSV report
csv = LoadTests/MediaIntensiveLoadTestResults/results